---
- name: wipe logic for web_app
  block:
  
    - name: remove the docker container
      docker_container:
        name: "{{ docker_container_name }}"
        state: absent

  when: web_app_full_wipe | bool
  tags:
    - wipe
