version: "3.8"

networks:
  default:
    name: loki

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "2"
    tag: "{{.ImageName}}|{{.Name}}"

x-deploy:
  &default-deploy
  resources:
    limits:
      memory: 100M

services:

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    logging: *default-logging
    deploy: *default-deploy

  prometheus:
    image: prom/prometheus:v2.30.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    logging: *default-logging
    deploy: *default-deploy
    
  app-python:
    build: ../app_python
    ports:
      - "8000:5000"
    logging: *default-logging
    volumes:
      - ./python-data:/app/data